#include "Renderer.h"
#include <d3dcompiler.h>
#include <cmath>
#include <cstring>
using namespace DirectX; using Microsoft::WRL::ComPtr;
namespace {
const char* VS=R"(
cbuffer C:register(b0){matrix wvp;float4 tint;float4 scene;};
struct I{float3 p:POSITION;float3 n:NORMAL;float4 c:COLOR;float e:TEXCOORD0;};
struct O{float4 p:SV_POSITION;float3 n:NORMAL;float4 c:COLOR;float e:TEXCOORD0;};
O main(I i){O o;float3 p=i.p;if(i.e>0.5&&i.e<1.5){float3 c=float3(0,78,150);p=c+(p-c)*scene.z;}if(i.e>1.5){float t=saturate(scene.y);float3 c=float3(-42+84*t,78,146);p=c+(p-float3(0,78,146));}o.p=mul(float4(p,1),wvp);o.n=i.n;o.c=i.c;o.e=i.e;return o;})";
const char* PS=R"(
cbuffer C:register(b0){matrix wvp;float4 tint;float4 scene;};
struct I{float4 p:SV_POSITION;float3 n:NORMAL;float4 c:COLOR;float e:TEXCOORD0;};
float4 main(I i):SV_TARGET{float3 n=normalize(i.n);float3 sun=normalize(float3(-.35,.82,-.45));float light=.22+.78*saturate(dot(n,sun));float3 c=i.c.rgb;if(i.e>0.5&&i.e<1.5){float glow=3.5+1.5*scene.z;c*=glow;return float4(saturate(c),1);}if(i.e>1.5){return float4(c*.018,1);}c*=light*tint.rgb;float d=saturate(i.p.z/max(i.p.w,.001));float fog=smoothstep(.25,.92,d)*.38;float3 sky=float3(.25,.48,.76)*(1-scene.x*.75);c=lerp(c,sky,fog);return float4(saturate(c),1);})";
bool compileShader(const char*s,const char*entry,const char*target,ComPtr<ID3DBlob>&b){ComPtr<ID3DBlob>err;return SUCCEEDED(D3DCompile(s,strlen(s),nullptr,nullptr,nullptr,entry,target,D3DCOMPILE_ENABLE_STRICTNESS,0,&b,&err));}
void tri(std::vector<Renderer::Vertex>&v,XMFLOAT3 a,XMFLOAT3 b,XMFLOAT3 c,XMFLOAT4 col,float e=0){XMVECTOR ab=XMLoadFloat3(&b)-XMLoadFloat3(&a),ac=XMLoadFloat3(&c)-XMLoadFloat3(&a);XMFLOAT3 n;XMStoreFloat3(&n,XMVector3Normalize(XMVector3Cross(ab,ac)));v.push_back({a,n,col,e});v.push_back({b,n,col,e});v.push_back({c,n,col,e});}
void cube(std::vector<Renderer::Vertex>&v,float x,float y,float z,float sx,float sy,float sz,XMFLOAT4 c){float a=x-sx*.5f,b=x+sx*.5f,d=z-sz*.5f,e=z+sz*.5f,t=y+sy;tri(v,{a,y,d},{b,y,d},{b,t,d},c);tri(v,{a,y,d},{b,t,d},{a,t,d},c);tri(v,{b,y,e},{a,y,e},{a,t,e},c);tri(v,{b,y,e},{a,t,e},{b,t,e},c);tri(v,{a,y,e},{a,y,d},{a,t,d},c);tri(v,{a,y,e},{a,t,d},{a,t,e},c);tri(v,{b,y,d},{b,y,e},{b,t,e},c);tri(v,{b,y,d},{b,t,e},{b,t,d},c);tri(v,{a,t,d},{b,t,d},{b,t,e},c);tri(v,{a,t,d},{b,t,e},{a,t,e},c);}
void sphere(std::vector<Renderer::Vertex>&v,float x,float y,float z,float r,XMFLOAT4 c,float e=0){for(int j=0;j<18;j++)for(int i=0;i<36;i++){float a=XM_2PI*i/36,b=XM_2PI*(i+1)/36,p=XM_PI*j/18-XM_PIDIV2,q=XM_PI*(j+1)/18-XM_PIDIV2;auto f=[&](float A,float P){return XMFLOAT3{x+r*cosf(P)*cosf(A),y+r*sinf(P),z+r*cosf(P)*sinf(A)};};auto A=f(a,p),B=f(b,p),C=f(b,q),D=f(a,q);tri(v,A,B,C,c,e);tri(v,A,C,D,c,e);}}
float h(float x,float z){float road=expf(-(x*x)/150.0f);return (sinf(x*.012f)*3.2f+cosf(z*.014f)*2.5f+sinf((x+z)*.024f)*1.8f)*(1-road);}
}
bool Renderer::Initialize(HWND w,int W,int H){width_=W;height_=H;return w&&W>0&&H>0&&CreateDevice(w)&&CreateTargets(W,H)&&CreateShaders()&&CreateRasterizerState()&&CreateGeometry();}
bool Renderer::CreateDevice(HWND w){DXGI_SWAP_CHAIN_DESC d{};d.BufferCount=2;d.BufferDesc.Width=width_;d.BufferDesc.Height=height_;d.BufferDesc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;d.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;d.OutputWindow=w;d.SampleDesc.Count=1;d.Windowed=TRUE;d.SwapEffect=DXGI_SWAP_EFFECT_FLIP_DISCARD;D3D_FEATURE_LEVEL l[]={D3D_FEATURE_LEVEL_11_0,D3D_FEATURE_LEVEL_10_0},q{};return SUCCEEDED(D3D11CreateDeviceAndSwapChain(nullptr,D3D_DRIVER_TYPE_HARDWARE,nullptr,0,l,2,D3D11_SDK_VERSION,&d,&swapChain_,&device_,&q,&context_));}
bool Renderer::CreateTargets(int W,int H){ComPtr<ID3D11Texture2D>b;if(FAILED(swapChain_->GetBuffer(0,IID_PPV_ARGS(&b)))||FAILED(device_->CreateRenderTargetView(b.Get(),nullptr,&renderTarget_)))return false;D3D11_TEXTURE2D_DESC d{};d.Width=W;d.Height=H;d.MipLevels=1;d.ArraySize=1;d.Format=DXGI_FORMAT_D24_UNORM_S8_UINT;d.SampleDesc.Count=1;d.BindFlags=D3D11_BIND_DEPTH_STENCIL;ComPtr<ID3D11Texture2D>x;if(FAILED(device_->CreateTexture2D(&d,nullptr,&x)))return false;return SUCCEEDED(device_->CreateDepthStencilView(x.Get(),nullptr,&depthView_));}
bool Renderer::CreateShaders(){ComPtr<ID3DBlob>a,b;if(!compileShader(VS,"main","vs_5_0",a)||!compileShader(PS,"main","ps_5_0",b))return false;if(FAILED(device_->CreateVertexShader(a->GetBufferPointer(),a->GetBufferSize(),nullptr,&vertexShader_)))return false;D3D11_INPUT_ELEMENT_DESC e[]={{"POSITION",0,DXGI_FORMAT_R32G32B32_FLOAT,0,0,D3D11_INPUT_PER_VERTEX_DATA,0},{"NORMAL",0,DXGI_FORMAT_R32G32B32_FLOAT,0,12,D3D11_INPUT_PER_VERTEX_DATA,0},{"COLOR",0,DXGI_FORMAT_R32G32B32A32_FLOAT,0,24,D3D11_INPUT_PER_VERTEX_DATA,0},{"TEXCOORD",0,DXGI_FORMAT_R32_FLOAT,0,40,D3D11_INPUT_PER_VERTEX_DATA,0}};if(FAILED(device_->CreateInputLayout(e,4,a->GetBufferPointer(),a->GetBufferSize(),&inputLayout_))||FAILED(device_->CreatePixelShader(b->GetBufferPointer(),b->GetBufferSize(),nullptr,&pixelShader_)))return false;D3D11_BUFFER_DESC d{};d.ByteWidth=sizeof(ConstantBufferData);d.Usage=D3D11_USAGE_DYNAMIC;d.BindFlags=D3D11_BIND_CONSTANT_BUFFER;d.CPUAccessFlags=D3D11_CPU_ACCESS_WRITE;return SUCCEEDED(device_->CreateBuffer(&d,nullptr,&constantBuffer_));}
bool Renderer::CreateRasterizerState(){D3D11_RASTERIZER_DESC d{};d.FillMode=D3D11_FILL_SOLID;d.CullMode=D3D11_CULL_NONE;d.DepthClipEnable=TRUE;return SUCCEEDED(device_->CreateRasterizerState(&d,&rasterizerState_));}
bool Renderer::CreateGeometry(){std::vector<Vertex>v;const int N=60;const float S=720,st=S/N;for(int z=0;z<N;z++)for(int x=0;x<N;x++){float x0=-S/2+x*st,x1=x0+st,z0=-70+z*st,z1=z0+st;float y0=h(x0,z0),y1=h(x1,z0),y2=h(x1,z1),y3=h(x0,z1);XMFLOAT4 c={.08f+.015f*(z%6),.24f+.012f*(x%7),.07f,1};tri(v,{x0,y0,z0},{x1,y1,z0},{x1,y2,z1},c);tri(v,{x0,y0,z0},{x1,y2,z1},{x0,y3,z1},c);}
cube(v,0,.30f,130,16,.28f,470,{.025f,.028f,.032f,1});cube(v,0,.48f,130,.22f,.035f,455,{.95f,.78f,.18f,1});cube(v,-7.25f,.47f,130,.08f,.025f,455,{.7f,.7f,.68f,1});cube(v,7.25f,.47f,130,.08f,.025f,455,{.7f,.7f,.68f,1});
for(int i=-6;i<=6;i++){float x=i*25,z=75+(i%3)*34,y=h(x,z),bh=18+(i+6)%4*6;cube(v,x,y,z,17,bh,17,{.24f+.02f*(i+6),.25f,.29f,1});cube(v,x,y+bh,z,18,1,18,{.10f,.10f,.12f,1});for(int row=0;row<3;row++)for(int side=-1;side<=1;side++)cube(v,x+side*4.5f,y+4+row*5,z-8.6f,2.2f,2.4f,.16f,{.55f,.70f,.78f,1});}
for(int i=0;i<12;i++){float z=15+i*34,x=(i%2?-3:3);cube(v,x,.58f,z,3.4f,1.25f,6.5f,{.48f+.03f*(i%4),.05f,.035f,1});cube(v,x,1.35f,z-.2f,2.5f,.75f,2.8f,{.07f,.15f,.19f,1});}
for(int i=0;i<16;i++){float x=-55+(i%8)*15,z=28+(i/8)*24,y=h(x,z);cube(v,x,y,z,1.0f,2.1f,.8f,{.12f,.18f,.55f,1});sphere(v,x,y+2.65f,z,.58f,{.66f,.46f,.33f,1});}
for(int i=-8;i<=8;i++){float x=i*45,z=455+abs(i)*4,bh=55+(i%4)*12;cube(v,x,0,z,60,bh,55,{.06f,.11f,.14f,1});}
sphere(v,0,78,150,21,{1,.45f,.02f,1},1);sphere(v,0,78,150,29,{1,.18f,.01f,1},.8f);sphere(v,-42,78,146,21,{.012f,.012f,.016f,1},2);vertexCount_=(UINT)v.size();D3D11_BUFFER_DESC d{};d.ByteWidth=(UINT)(v.size()*sizeof(Vertex));d.Usage=D3D11_USAGE_DEFAULT;d.BindFlags=D3D11_BIND_VERTEX_BUFFER;D3D11_SUBRESOURCE_DATA s{};s.pSysMem=v.data();return SUCCEEDED(device_->CreateBuffer(&d,&s,&vertexBuffer_));}
void Renderer::Resize(int W,int H){if(!swapChain_||W<1||H<1)return;context_->OMSetRenderTargets(0,nullptr,nullptr);renderTarget_.Reset();depthView_.Reset();width_=W;height_=H;if(SUCCEEDED(swapChain_->ResizeBuffers(0,W,H,DXGI_FORMAT_UNKNOWN,0)))CreateTargets(W,H);}
void Renderer::BeginFrame(float e){float k=1-e*.78f;float c[]={.07f*k+.01f,.17f*k+.01f,.34f*k+.015f,1};context_->ClearRenderTargetView(renderTarget_.Get(),c);context_->ClearDepthStencilView(depthView_.Get(),D3D11_CLEAR_DEPTH,1,0);context_->OMSetRenderTargets(1,renderTarget_.GetAddressOf(),depthView_.Get());D3D11_VIEWPORT p{0,0,(float)width_,(float)height_,0,1};context_->RSSetViewports(1,&p);context_->RSSetState(rasterizerState_.Get());}
void Renderer::Draw(const XMMATRIX&view,const XMMATRIX&projection,float time,float eclipse){D3D11_MAPPED_SUBRESOURCE m{};if(SUCCEEDED(context_->Map(constantBuffer_.Get(),0,D3D11_MAP_WRITE_DISCARD,0,&m))){auto*c=(ConstantBufferData*)m.pData;c->worldViewProjection=XMMatrixTranspose(view*projection);float d=1-eclipse*.78f;c->tint={d,d*.97f,d*.92f,1};float grow=1.0f+0.65f*(0.5f+0.5f*sinf(time*.7f));c->scene={eclipse,eclipse,grow,time};context_->Unmap(constantBuffer_.Get(),0);}UINT stride=sizeof(Vertex),offset=0;context_->IASetInputLayout(inputLayout_.Get());context_->IASetVertexBuffers(0,1,vertexBuffer_.GetAddressOf(),&stride,&offset);context_->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);context_->VSSetShader(vertexShader_.Get(),nullptr,0);context_->PSSetShader(pixelShader_.Get(),nullptr,0);context_->VSSetConstantBuffers(0,1,constantBuffer_.GetAddressOf());context_->PSSetConstantBuffers(0,1,constantBuffer_.GetAddressOf());context_->Draw(vertexCount_,0);}
void Renderer::EndFrame(){swapChain_->Present(1,0);}
