#include "Renderer.h"
#include <d3dcompiler.h>
#include <cmath>
#include <cstring>
using namespace DirectX;using Microsoft::WRL::ComPtr;
namespace{
const char*vs=R"(cbuffer C:register(b0){matrix wvp;float4 tint;};struct I{float3 p:POSITION;float3 n:NORMAL;float4 c:COLOR;float e:TEXCOORD0;};struct O{float4 p:SV_POSITION;float3 n:NORMAL;float4 c:COLOR;float e:TEXCOORD0;};O main(I i){O o;o.p=mul(float4(i.p,1),wvp);o.n=i.n;o.c=i.c;o.e=i.e;return o;})";
const char*ps=R"(cbuffer C:register(b0){matrix wvp;float4 tint;};struct I{float4 p:SV_POSITION;float3 n:NORMAL;float4 c:COLOR;float e:TEXCOORD0;};float4 main(I i):SV_TARGET{float s=saturate(dot(normalize(i.n),normalize(float3(-.3,.85,-.2))));float3 c=i.c.rgb*(.3+.7*s)+i.c.rgb*i.e*3;return float4(saturate(c*tint.rgb),1);})";
bool comp(const char*s,const char*e,const char*t,ComPtr<ID3DBlob>&b){ComPtr<ID3DBlob>x;return SUCCEEDED(D3DCompile(s,strlen(s),nullptr,nullptr,nullptr,e,t,D3DCOMPILE_ENABLE_STRICTNESS,0,&b,&x));}
void tri(std::vector<Renderer::Vertex>&v,XMFLOAT3 a,XMFLOAT3 b,XMFLOAT3 c,XMFLOAT4 col,float em=0){XMFLOAT3 n;XMStoreFloat3(&n,XMVector3Normalize(XMVector3Cross(XMLoadFloat3(&b)-XMLoadFloat3(&a),XMLoadFloat3(&c)-XMLoadFloat3(&a))));v.push_back({a,n,col,em});v.push_back({b,n,col,em});v.push_back({c,n,col,em});}
void cube(std::vector<Renderer::Vertex>&v,float x,float y,float z,float sx,float sy,float sz,XMFLOAT4 c){float a=x-sx/2,b=x+sx/2,d=z-sz/2,e=z+sz/2;tri(v,{a,y,d},{b,y,d},{b,y+sy,d},c);tri(v,{a,y,d},{b,y+sy,d},{a,y+sy,d},c);tri(v,{b,y,e},{a,y,e},{a,y+sy,e},c);tri(v,{b,y,e},{a,y+sy,e},{b,y+sy,e},c);tri(v,{a,y,e},{a,y,d},{a,y+sy,d},c);tri(v,{a,y,e},{a,y+sy,d},{a,y+sy,e},c);tri(v,{b,y,d},{b,y,e},{b,y+sy,e},c);tri(v,{b,y,d},{b,y+sy,e},{b,y+sy,d},c);tri(v,{a,y+sy,d},{b,y+sy,d},{b,y+sy,e},c);tri(v,{a,y+sy,d},{b,y+sy,e},{a,y+sy,e},c);}
void sph(std::vector<Renderer::Vertex>&v,float x,float y,float z,float r,XMFLOAT4 c,float em){for(int j=0;j<12;j++)for(int i=0;i<24;i++){float A=XM_2PI*i/24,B=XM_2PI*(i+1)/24,P=XM_PI*j/12-XM_PIDIV2,Q=XM_PI*(j+1)/12-XM_PIDIV2;auto p=[&](float a,float q){return XMFLOAT3{x+r*cosf(q)*cosf(a),y+r*sinf(q),z+r*cosf(q)*sinf(a)};};auto a=p(A,P),b=p(B,P),cc=p(B,Q),d=p(A,Q);tri(v,a,b,cc,c,em);tri(v,a,cc,d,c,em);}}
}
bool Renderer::Initialize(HWND w,int W,int H){if(!w||W<1||H<1)return false;width_=W;height_=H;return CreateDevice(w)&&CreateTargets(W,H)&&CreateShaders()&&CreateRasterizerState()&&CreateGeometry();}
bool Renderer::CreateDevice(HWND w){DXGI_SWAP_CHAIN_DESC d{};d.BufferCount=2;d.BufferDesc.Width=width_;d.BufferDesc.Height=height_;d.BufferDesc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;d.BufferUsage=DXGI_USAGE_RENDER_TARGET_OUTPUT;d.OutputWindow=w;d.SampleDesc.Count=1;d.Windowed=TRUE;d.SwapEffect=DXGI_SWAP_EFFECT_FLIP_DISCARD;D3D_FEATURE_LEVEL l[]={D3D_FEATURE_LEVEL_11_0,D3D_FEATURE_LEVEL_10_0},q{};HRESULT h=D3D11CreateDeviceAndSwapChain(nullptr,D3D_DRIVER_TYPE_HARDWARE,nullptr,0,l,2,D3D11_SDK_VERSION,&d,&swapChain_,&device_,&q,&context_);if(FAILED(h))h=D3D11CreateDeviceAndSwapChain(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,l,2,D3D11_SDK_VERSION,&d,&swapChain_,&device_,&q,&context_);return SUCCEEDED(h);}
bool Renderer::CreateTargets(int W,int H){ComPtr<ID3D11Texture2D>b;if(FAILED(swapChain_->GetBuffer(0,IID_PPV_ARGS(&b))))return false;if(FAILED(device_->CreateRenderTargetView(b.Get(),nullptr,&renderTarget_)))return false;D3D11_TEXTURE2D_DESC d{};d.Width=W;d.Height=H;d.MipLevels=1;d.ArraySize=1;d.Format=DXGI_FORMAT_D24_UNORM_S8_UINT;d.SampleDesc.Count=1;d.BindFlags=D3D11_BIND_DEPTH_STENCIL;ComPtr<ID3D11Texture2D>dep;if(FAILED(device_->CreateTexture2D(&d,nullptr,&dep)))return false;return SUCCEEDED(device_->CreateDepthStencilView(dep.Get(),nullptr,&depthView_));}
bool Renderer::CreateShaders(){ComPtr<ID3DBlob>a,b;if(!comp(vs,"main","vs_5_0",a)||!comp(ps,"main","ps_5_0",b))return false;if(FAILED(device_->CreateVertexShader(a->GetBufferPointer(),a->GetBufferSize(),nullptr,&vertexShader_)))return false;D3D11_INPUT_ELEMENT_DESC e[]={{"POSITION",0,DXGI_FORMAT_R32G32B32_FLOAT,0,0,D3D11_INPUT_PER_VERTEX_DATA,0},{"NORMAL",0,DXGI_FORMAT_R32G32B32_FLOAT,0,12,D3D11_INPUT_PER_VERTEX_DATA,0},{"COLOR",0,DXGI_FORMAT_R32G32B32A32_FLOAT,0,24,D3D11_INPUT_PER_VERTEX_DATA,0},{"TEXCOORD",0,DXGI_FORMAT_R32_FLOAT,0,40,D3D11_INPUT_PER_VERTEX_DATA,0}};if(FAILED(device_->CreateInputLayout(e,4,a->GetBufferPointer(),a->GetBufferSize(),&inputLayout_)))return false;if(FAILED(device_->CreatePixelShader(b->GetBufferPointer(),b->GetBufferSize(),nullptr,&pixelShader_)))return false;D3D11_BUFFER_DESC d{};d.ByteWidth=sizeof(ConstantBufferData);d.Usage=D3D11_USAGE_DYNAMIC;d.BindFlags=D3D11_BIND_CONSTANT_BUFFER;d.CPUAccessFlags=D3D11_CPU_ACCESS_WRITE;return SUCCEEDED(device_->CreateBuffer(&d,nullptr,&constantBuffer_));}
bool Renderer::CreateRasterizerState(){D3D11_RASTERIZER_DESC d{};d.FillMode=D3D11_FILL_SOLID;d.CullMode=D3D11_CULL_NONE;d.DepthClipEnable=TRUE;return SUCCEEDED(device_->CreateRasterizerState(&d,&rasterizerState_));}
bool Renderer::CreateGeometry(){std::vector<Vertex>v;auto H=[](float x,float z){return sinf(x*.012f)*5.5f+cosf(z*.015f)*4+sinf((x+z)*.028f)*2.2f;};auto V=[&](float x,float z){float y=H(x,z),e=.3f,hx=(H(x+e,z)-H(x-e,z))/(2*e),hz=(H(x,z+e)-H(x,z-e))/(2*e);XMFLOAT3 n;XMStoreFloat3(&n,XMVector3Normalize(XMVectorSet(-hx,1,-hz,0)));return Vertex{{x,y,z},n,{.16f,.40f,.12f,1},0};};const int G=140;const float S=700;for(int z=0;z<G-1;z++)for(int x=0;x<G-1;x++){float x0=-S/2+S*x/(G-1),x1=-S/2+S*(x+1)/(G-1),z0=-S/2+S*z/(G-1),z1=-S/2+S*(z+1)/(G-1);auto a=V(x0,z0),b=V(x1,z0),c=V(x1,z1),d=V(x0,z1);v.insert(v.end(),{a,b,c,a,c,d});}
// Roads
cube(v,0,H(0,80)+.12f,80,12,.18f,650,{.045f,.045f,.05f,1});cube(v,80,H(80,0)+.13f,0,650,.18f,12,{.045f,.045f,.05f,1});
// Buildings
for(int i=-2;i<=2;i++){float x=i*30;cube(v,x,H(x,35),35,18,18,{.38f,.40f,.44f,1});cube(v,x,H(x,58),58,16,24,{.50f,.30f,.20f,1});}
// Cars
for(int i=-3;i<=3;i++){float x=i*20;cube(v,x,H(x,62)+.3f,62,4,1.3f,7,{.65f,.08f,.04f,1});cube(v,x,H(x,62)+1.5f,62,3,1,3.5f,{.12f,.15f,.20f,1});}
// NPCs
for(int i=0;i<8;i++){float x=-40+i*11,z=15+(i%2)*12,y=H(x,z);cube(v,x,y,z,1.1f,2,1,{.12f,.22f,.55f,1});sph(v,x,y+2.55f,z,.5f,{.72f,.50f,.36f,1},0);}
// Sun grows through the sky; moon is positioned in front for eclipse.
sph(v,0,92,150,8,{1,.68f,.08f,1},1);sph(v,0,92,142,6,{.01f,.01f,.015f,1},0);
vertexCount_=(UINT)v.size();D3D11_BUFFER_DESC d{};d.ByteWidth=(UINT)(v.size()*sizeof(Vertex));d.Usage=D3D11_USAGE_DEFAULT;d.BindFlags=D3D11_BIND_VERTEX_BUFFER;D3D11_SUBRESOURCE_DATA s{};s.pSysMem=v.data();return SUCCEEDED(device_->CreateBuffer(&d,&s,&vertexBuffer_));}
void Renderer::Resize(int W,int H){if(!swapChain_||W<1||H<1)return;context_->OMSetRenderTargets(0,nullptr,nullptr);renderTarget_.Reset();depthView_.Reset();width_=W;height_=H;if(SUCCEEDED(swapChain_->ResizeBuffers(0,W,H,DXGI_FORMAT_UNKNOWN,0)))CreateTargets(W,H);}
void Renderer::BeginFrame(float e){if(!context_)return;e=e<0?0:e>1?1:e;float c[]={.07f*(1-e)+.012f*e,.15f*(1-e)+.018f*e,.28f*(1-e)+.025f*e,1};context_->ClearRenderTargetView(renderTarget_.Get(),c);context_->ClearDepthStencilView(depthView_.Get(),D3D11_CLEAR_DEPTH|D3D11_CLEAR_STENCIL,1,0);context_->OMSetRenderTargets(1,renderTarget_.GetAddressOf(),depthView_.Get());D3D11_VIEWPORT p{0,0,(float)width_,(float)height_,0,1};context_->RSSetViewports(1,&p);context_->RSSetState(rasterizerState_.Get());}
void Renderer::Draw(const XMMATRIX&view,const XMMATRIX&projection,float sunScale,float eclipse){if(!context_||!constantBuffer_)return;D3D11_MAPPED_SUBRESOURCE m{};if(SUCCEEDED(context_->Map(constantBuffer_.Get(),0,D3D11_MAP_WRITE_DISCARD,0,&m))){auto*c=(ConstantBufferData*)m.pData;float dim=1-eclipse*.72f;c->worldViewProjection=XMMatrixTranspose(view*projection);c->tint={dim,dim*.96f,dim*.9f,1};context_->Unmap(constantBuffer_.Get(),0);}UINT st=sizeof(Vertex),of=0;context_->IASetInputLayout(inputLayout_.Get());context_->IASetVertexBuffers(0,1,vertexBuffer_.GetAddressOf(),&st,&of);context_->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);context_->VSSetShader(vertexShader_.Get(),nullptr,0);context_->VSSetConstantBuffers(0,1,constantBuffer_.GetAddressOf());context_->PSSetShader(pixelShader_.Get(),nullptr,0);context_->PSSetConstantBuffers(0,1,constantBuffer_.GetAddressOf());context_->Draw(vertexCount_,0);}
void Renderer::EndFrame(){if(swapChain_)swapChain_->Present(1,0);}
